Add specific job to test signature for a built image

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -276,6 +276,12 @@ stages:
   - name: DEPLOYMENT_FILE
     value: deployment.yml
     type: text
+  - name: BUILD_SIGNER
+    value: ${BUILD_SIGNER}
+    type: text
+  - name: VALIDATION_SIGNER
+    value: ${VALIDATION_SIGNER}
+    type: text
   - name: APP_URL
     value: undefined
     type: text  
@@ -297,7 +303,23 @@ stages:
       ibmcloud cr login
       # configure DCT and inspect the image
       export DOCKER_CONTENT_TRUST_SERVER=https://${REGISTRY_URL}:4443
-      docker trust inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
+      docker trust inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} | tee _image_inspect.json
+
+      # Check if the Builder signature is present
+      if jq -e ".[] | select(.Name=\"$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG\") | .SignedTags[] | select(.SignedTag=\"$IMAGE_TAG\") | select (.Signers[] | contains(\"$BUILD_SIGNER\"))" _image_inspect.json; then
+        echo "Signature $BUILD_SIGNER found"
+      else
+        echo "Signature $BUILD_SIGNER not found"
+        exit 1
+      fi
+
+      # Check if the Validation signature is present
+      if jq -e ".[] | select(.Name=\"$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG\") | .SignedTags[] | select(.SignedTag=\"$IMAGE_TAG\") | select (.Signers[] | contains(\"$VALIDATION_SIGNER\"))" _image_inspect.json; then
+        echo "Signature $VALIDATION_SIGNER found"
+      else
+        echo "Signature $VALIDATION_SIGNER not found"
+        exit 1
+      fi
   - name: Deploy to Kubernetes
     type: deployer
     target:
